#!/bin/bash
#SBATCH --account=***
#SBATCH --job-name=prrtagsCF0
#SBATCH --partition=large
#SBATCH --time=14:00:00
#SBATCH --mem=8G
#SBATCH --output=./process_radtags.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=***
#SBATCH --cpus-per-task=10

#=======Load the module/software Environment
module load Stacks
##Angela sent me a zip file containing demultiplexed data. Using fastqc I realized the sequence length varies bewteen samples.
##De novo assembly of loci using Stacks should be done on sequences with the same length. As we always trim our GBS sequences to 68 pb
##to remove the barcodes, I did the same here on Angela's demultiplexed reads: 

##======My_Commands================

process_radtags	-f	./Dur4mi10.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi10.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi11.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi11.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi12.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi12.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi14.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi14.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi19.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi19.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi1.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi1.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi20.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi20.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi23.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi23.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi24.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi24.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi30.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi30.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi8.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Dur4mi8.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic10.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic10.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic11.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic11.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic12.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic12.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic13.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic13.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic14.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic14.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic15.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic15.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic16.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic16.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic20.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic20.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic22.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic22.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic26.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic26.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic27.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic27.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic28.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic28.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic29.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic29.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic30.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic30.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic4.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic4.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic5.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic5.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic6.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic6.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic7.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic7.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic8.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic8.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic9.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurBic9.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurFis3.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurFis3.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurFis7.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurFis7.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurLad2.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurLad2.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurLad3.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurLad3.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurLad4.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurLad4.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurLad6.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurLad6.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa11.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa11.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa21.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa21.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa22.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa22.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa23.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa23.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa24.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa24.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa25.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa25.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa26.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa26.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa27.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa27.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa28.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa28.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa29.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa29.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa30.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa30.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa3.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurRoa3.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH10.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH10.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH11.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH11.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH12.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH12.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH13.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH13.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH15.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH15.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH19.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH19.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH1.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH1.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH20.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH20.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH21.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH21.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH22.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH22.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH23.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH23.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH24.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH24.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH25.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH25.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH26.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH26.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH27.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH27.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH29.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH29.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH3.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH3.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH5.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH5.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH7.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH7.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH8.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH8.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH9.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./DurStH9.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH10.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH10.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH11.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH11.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH12.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH12.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH13.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH13.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH14.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH14.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH15.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH15.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH16.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH16.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH17.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH17.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH18.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH18.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH19.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH19.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH1.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH1.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH20.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH20.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH21.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH21.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH22.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH22.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH23.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH23.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH24.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH24.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH25.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH25.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH2.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH2.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH3.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH3.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH4.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH4.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH5.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH5.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH6.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH6.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH7.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH7.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH8.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH8.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH9.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./KH9.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass10.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass10.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass11.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass11.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass12.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass12.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass13.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass13.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass14.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass14.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass15.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass15.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass16.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass16.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass17.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass17.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass18.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass18.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass19.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass19.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass1.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass1.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass20.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass20.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass21.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass21.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass22.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass22.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass23.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass23.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass24.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass24.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass25.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass25.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass2.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass2.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass3.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass3.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass4.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass4.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass5.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass5.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass6.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass6.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass7.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass7.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass8.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass8.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass9.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./Pass9.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC10.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC10.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC11.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC11.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC12.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC12.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC13.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC13.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC14.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC14.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC15.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC15.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC16.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC16.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC17.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC17.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC18.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC18.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC19.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC19.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC1.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC1.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC20.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC20.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC21.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC21.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC22.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC22.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC23.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC23.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC24.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC24.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC25.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC25.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC2.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC2.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC3.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC3.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC4.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC4.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC5.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC5.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC6.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC6.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC7.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC7.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC8.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC8.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC9.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./SC9.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA10.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA10.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA11.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA11.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA12.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA12.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA13.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA13.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA14.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA14.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA15.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA15.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA17.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA17.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA18.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA18.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA19.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA19.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA1.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA1.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA21.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA21.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA22.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA22.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA23.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA23.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA24.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA24.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA25.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA25.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA2.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA2.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA3.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA3.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA4.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA4.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA5.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA5.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA6.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA6.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA7.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA7.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA8.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA8.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA9.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TA9.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TV1.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TV1.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TV2.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TV2.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TV3.trimmed_R1_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/
process_radtags	-f	./TV3.trimmed_R2_.fastq.gz	-t	68	-e	pstI	-r	-c	-q	-o	./output/