#!/bin/bash
##samples removed after quality control using fastqc and multiqc. These samples had less than 0.5 million raw reads.
rm	KH1.fq.gz
rm	KH24.fq.gz
rm	Pass13.fq.gz
rm	Pass20.fq.gz
rm	Pass24.fq.gz
rm	Pass8.fq.gz
rm	SC10.fq.gz
rm	SC12.fq.gz
rm	SC13.fq.gz
rm	SC14.fq.gz
rm	SC15.fq.gz
rm	SC17.fq.gz
rm	SC19.fq.gz
rm	SC2.fq.gz
rm	SC20.fq.gz
rm	SC21.fq.gz
rm	SC22.fq.gz
rm	SC23.fq.gz
rm	SC24.fq.gz
rm	SC25.fq.gz
rm	SC3.fq.gz
rm	SC6.fq.gz
rm	TA1.fq.gz
rm	TA11.fq.gz
rm	TA12.fq.gz
rm	TA13.fq.gz
rm	TA14.fq.gz
rm	TA15.fq.gz
rm	TA18.fq.gz
rm	TA2.fq.gz
rm	TA21.fq.gz
rm	TA22.fq.gz
rm	TA23.fq.gz
rm	TA24.fq.gz
rm	TA25.fq.gz
rm	TA3.fq.gz
rm	TA6.fq.gz
rm	TA8.fq.gz
rm	TA9.fq.gz
rm	TV1.fq.gz
rm	TV3.fq.gz
rm Dur4mi1.fq.gz
rm DurBic28.fq.gz
rm DurBic29.fq.gz
rm DurBic5.fq.gz
rm DurBic8.fq.gz
rm DurFis7.fq.gz
rm DurLad6.fq.gz
rm DurStH19.fq.gz