#!/bin/bash
rm	Mac4ml36.fq.gz
rm	Mac4ml41.fq.gz
rm	Mac4ml42.fq.gz
rm	MacEdn1.fq.gz
rm	MacEdn2.fq.gz
rm	MacFish4.fq.gz
rm	MacFish5.fq.gz
rm	MacFish7.fq.gz
rm	MacFish8.fq.gz
rm	MacKey1.fq.gz
rm	MacKey2.fq.gz
rm	MacKey3.fq.gz
rm	MacKey5.fq.gz
rm	MacKey6.fq.gz
rm	MacKey8.fq.gz
rm	MacShel10.fq.gz
rm	MacShel11.fq.gz
rm	MacShel13.fq.gz
rm	MacShel14.fq.gz
rm	MacShel6.fq.gz
rm	MacShel8.fq.gz
rm	MacShel9.fq.gz